# Generated by Django 5.0.2 on 2024-04-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsletterr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletterr',
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
